### ISSUE TITLE
missing temp.css

### ISSUE THREAD

**Issue by tomgermany** [toolsforresearch/tfr_responsive#1]
Hello Tammo,

just made a test with your template. Great Work, looks good...

Only one simple issue:
- Lime Survey 
- one survey
- one question
  Start with the test survey and i see:

temp.css is called, but not there

Cu
Tom
(Sorry for bad english.....)

**Comment by tammoterhark** [comment]
Peter, zonder dat de GITHUB ergens gemeld werd als aanwezig, zijn er blijkbaar mensen die hem weten te vinden. Kun je in wijzigingen die de FREE-only versie betreffen alsjeblieft met voorrang aanpakken? Dan kunnen we verder reclame maken hiervoor.

**Comment by tammoterhark** [comment]
Hi Tom, you found our repo, even though we did not announce it anywhere! You sent us two issues, they will be dealt with, we hope to release a new version soon. This is still under construction!

Thanks for your interest in our template!

**Comment by tammoterhark** [comment]
Will be fixed in next version, available next week.

**Comment by tammoterhark** [comment]
temp.css has been removed in newest release
