### ISSUE TITLE
Very long sliders on higher display resolutions.

### ISSUE THREAD

**Issue by HellaHepp** [toolsforresearch/tfr_responsive#11]
Maybe not a "real" issue, but why not optimize slider design for higher display resolutions?
Just a simple suggestion:

Smaller display resolution (as it is right now): 
|- - -  - - - - -|
dark bright

Higher display resolution (would avoid too long slider and also reduce scrolling efforts ;-)):
dark - - bright

**Comment by tammoterhark** [comment]
Thanks HellaHepp, for these (4) suggestions. We will discuss them and report back!

**Comment by tammoterhark** [comment]
Hi Hella, we decided to leave this as is, because we have no easy way of finding out the width needed. Than any choice from us would be arbitrary.
