### ISSUE TITLE
IE11 issues

### ISSUE THREAD

**Issue by mikerogerz** [toolsforresearch/tfr_responsive#12]
Your responsive template has been working great for us, but we've now had reports of issues specific to IE11 (not sure about other versions, since this is the only version we have available to test with).
- No survey progress bar.
- Unable to select radio buttons for Array type questions.
- Branched (decision-based) questions not showing up dynamically. These only work if you go to the next page and then go back, where it's not longer dynamically generated.

**Comment by tammoterhark** [comment]
Mike, are your sure that /js/template.js is available and gets loaded at the page? You reports seems to indicate that this file does not get loaded.

**Comment by mikerogerz** [comment]
It's working correctly in Chrome and FF, so I don't think that's the
issue... Unless it's not loading the js file for some reason.

I'll try to investigate further, since this was a report from a user and I
haven't been able to test yet myself.

**Comment by tammoterhark** [comment]
I've just been testing in IE11 with our demo survey at:
https://survey.toolsforresearch.com/index.php/123456/lang-en

and we see no problems. Maybe your user had disabled Javascript in the browser?

**Comment by mikerogerz** [comment]
That's great to hear... I'll see if that's the issue. I would be surprised
though since the web application working along-side of LS is heavy on the
js. I'll report back once I find out more.

Thanks.

**Comment by tammoterhark** [comment]
Could not reproduce
