### ISSUE TITLE
[installation] first time import of template error: 

### ISSUE THREAD

**Issue by raramuridesign** [toolsforresearch/tfr_responsive#14]
Limesurvey Version 2.06+ Build 150629

When installing the template for the first time the following error occurs at the bottom
This causes the template to not work
Please let us know if this can be fixed.

thanks

![ss-lime](https://cloud.githubusercontent.com/assets/902376/8627754/6fc4f70a-274d-11e5-9303-1154c30e0991.png)

**Comment by tammoterhark** [comment]
Hi raramuridesign,

Can you try to upload via FTP? I remember we earlier also encountered this once. Evening here and work computer is in the office...

**Comment by Jan-E** [comment]
It looks like @raramuridesign downloaded the git head, hence the tfr_responsive-master. Best place to download the template: https://www.toolsforresearch.com/limesurvey-responsive-template

**Comment by raramuridesign** [comment]
Thanks this is now working
;-)
