### ISSUE TITLE
Change of the number of display columns is not possible

### ISSUE THREAD

**Issue by kalckhoff** [toolsforresearch/tfr_responsive#15]
Hello,

I guess there is an issue if you try to change the number of shown display columns. It's just possible to have one column, if you change the setting to two columns, it doesn't take any effect.

![display_columns](https://cloud.githubusercontent.com/assets/12551042/8646695/44fa7552-2952-11e5-97b4-66b07872ebf2.JPG)

**Comment by tammoterhark** [comment]
We are working on that, this will be solved (at least for 2, 3, 4, 6 colums) in the next release.

**Comment by tammoterhark** [comment]
Just for the time being, a workaround might be to put something like this in the template.js:

```
$(document).ready(function ($) {
$( ".cols-2-ul" ).wrap( "<div class='col-sm-12 col-md-6'></div>" );
$( ".cols-3-ul" ).wrap( "<div class='col-sm-12 col-md-4'></div>" );
$( ".cols-4-ul" ).wrap( "<div class='col-sm-12 col-md-3'></div>" );
$( ".cols-6-ul" ).wrap( "<div class='col-sm-12 col-md-2'></div>" );
});
```

**Comment by kalckhoff** [comment]
that sound great, do you have a plan (roadmap) when the next release will be ?

**Comment by tammoterhark** [comment]
This will be in August, since part of our capacitiy is on holidays now...

**Comment by kalckhoff** [comment]
Thank You very much, the workaround is working, really well !!!
I just found two further points.
1. Sometimes (I don't know in which circumstances it happen, used the chrome browser) the circle-pictures will not load correctly - mobile and desktop - I had to reload or delete my browser caches to fix it.
2. If you build in the column-fix in the next release, you may can prepare that the free-text-answers have the underscore on the same line like on the other sides. But it is really just a little optical enhancement ;)

Any way, thank you for your great work :)

![display_columns_2](https://cloud.githubusercontent.com/assets/12551042/8647570/6531efd8-2959-11e5-98aa-240bdfd3856d.JPG)

**Comment by tammoterhark** [comment]
In our release 1.5.1 we have introduced 2, 3, 4, 5,6 columns. But remember: this template was focussed on mobile use, so clumns will most likely not be preferable for your users.

When you use it on a desktop/laptop, columns may come in handy, though...
