### ISSUE TITLE
mobile presentation of an dual array layout is not correct

### ISSUE THREAD

**Issue by kalckhoff** [toolsforresearch/tfr_responsive#16]
Hello,

there I found an other problem. The presentation of a dual array is not really accurate on a mobile device. Maybe it is not even possible to get it right. But for example if the second table of the dual array would be shown among themselves, it would work for most cases I guess.

![left_part_dual_array](https://cloud.githubusercontent.com/assets/12551042/8656009/3c0c1020-2995-11e5-80e3-1f47f17baf35.png)
![right_part_dual_array](https://cloud.githubusercontent.com/assets/12551042/8656010/3eb5a93a-2995-11e5-9a85-cf8a569f1340.png)

**Comment by tammoterhark** [comment]
I guess that working with Arrays on a mobile phone will always stay a challenge....

We will look into it, but we cannot promise good results for small screens. Anyway: I would never use large arrays when I would suspect that people would fill in on mobile phone...

**Comment by PeterEmil** [comment]
Tammo - als deze persoon de free template heeft gaat die array nooit werken; die is alleen premium :)

Hartelijke groet
Peter

pixelliquid aka peter emil
:: visual candy ::

06 . 422 700 59
studio unit D
Spaarne 17
2011 CD Haarlem
googlemaps <http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=pixelliquid+haarlem&sll=37.0625,-95.677068&sspn=39.184175,79.013672&ie=UTF8&hq=pixelliquid&hnear=Haarlem,+North+Holland,+The+Netherlands&ll=52.382594,4.634771&spn=0.007387,0.01929&z=16&iwloc=B>
skype: pixelliquid
linkedin: peteremil <https://nl.linkedin.com/in/peteremil>
http://www.pixelliquid.com <http://www.pixelliquid.com/>

**Comment by pixelliquid** [comment]
We made the arrays responsive in our premium template: http://www.limesurvey-templates.com/limesurvey-template-responsive-p-59.html

**Comment by tammoterhark** [comment]
You are absolutely right!

**Comment by tammoterhark** [comment]
Dual arrays not advised on mobile surveys.
