### ISSUE TITLE
Problems with loading of interactive elements (checkboxes, radioboxes etc.)

### ISSUE THREAD

**Issue by boriginal** [toolsforresearch/tfr_responsive#17]
When testing the template with low internet speed the interactive elements won't be displayed.
In Chrome (attached picture) and Firefox a rectangle is displayed instead, in IE nothing.

![elements](https://cloud.githubusercontent.com/assets/7590910/8743346/360cf942-2c6e-11e5-8978-5bcf631964bb.jpg)

**Comment by tammoterhark** [comment]
This may have to do with the stylesheet being too large. We will look into it. Thanks for reporting.

**Comment by tammoterhark** [comment]
In our newest release we have been able to "shrink" the css to about 50%. Please check the release notes at:
