### ISSUE TITLE
After LimeSurvey upgrade to 2.50 version, template doesn't work

### ISSUE THREAD

**Issue by salvatorecordiano** [toolsforresearch/tfr_responsive#19]
I update LimeSurvey to 2.50 versione, but template doesn't work

**Comment by pixelliquid** [comment]
Hi Salvatore, thanks for your interest in our template. We are working on a brand new release which will be fully compatible with LimeSurvey v2.50. Keep an eye open on this repository and [https://www.toolsforresearch.com/limesurvey-responsive-template](url)

**Comment by hartundweich** [comment]
Hi, is there a plan when we can expect the new responsive template?

**Comment by tammoterhark** [comment]
We are working along with the LimeSurvey development team in cleaning up the HTML that is outputted by LimeSurvey. This is at several places somewhat messy. We therefore cannot come with a new version of our template yet. We hope to be able to do that within two months, but I cannot guaratee that. I'm sorry. 

BTW: the current default template is better than what it was in 2.06, but I would also like to see the HTML be stable enough to be able to define a new template for that.

**Comment by hartundweich** [comment]
Thank you for your response - it's good to know, that there is a plan to make you templates work with limesurvey 2.50 - we have tried here for a few hours to make it possible - but you are right, too much changed in limesurvey 2.50 - and we would prefer to use responsive templates based on bootstrap. So still waiting for your new version :+1:

**Comment by tammoterhark** [comment]
Just hang on in there for a while: developers at LimeSurvey and in the community are completely overhauling the HTML structure of LimeSurvey output. This will have a great impact on existing templates. In fact it will probably make them unusable. The good news it, that is will be much easier to define your own templates.

The new version with a templating engine is planned for Spring 2017.

**Comment by salvatorecordiano** [comment]
This issue is too old. I close it
