### ISSUE TITLE
No Issuses, maybe little help

### ISSUE THREAD

**Issue by tomgermany** [toolsforresearch/tfr_responsive#2]
I changed in welcome.pstpl 
from
<img class="logo center-block" src="/upload/templates/tfr-responsive/logo-tfr.png" 
to
<img class="logo center-block" src="{TEMPLATEURL}logo-tfr.png"
...
No more errors in searching logo-trf.png
Cu
Tom

**Comment by tammoterhark** [comment]
In the premium version we will fix this. 

We like to keep the branding ours, although you are free to change this.
