### ISSUE TITLE
Problem with dual scales array

### ISSUE THREAD

**Issue by tammoterhark** [toolsforresearch/tfr_responsive#22]
https://www.limesurvey.org/forum/can-i-do-this-with-limesurvey/111626-question-on-headers-for-array-dual-scales-with-the-tfr-responsive-template#157982

Weet je of deze ooit aangepakt is?

**Comment by Jan-E** [comment]
https://github.com/toolsforresearch/tfr_responsive/issues/16#issuecomment-127282989 en https://github.com/toolsforresearch/tfr-responsive-1x/issues/18

**Comment by pixelliquid** [comment]
Zie https://github.com/toolsforresearch/tfr-responsive-1x/issues/18
