### ISSUE TITLE
Missing sass source files

### ISSUE THREAD

**Issue by grakic** [toolsforresearch/tfr_responsive#5]
Hi,

I would like to contribute some changes but I can not do this without sass source files. Do you plan to make them available?

Best,
Goran

**Comment by tammoterhark** [comment]
Hi Goran, we do not plan to make the SASS files available, but if you want to make a contribution in css we will be happy to incorporate that if it fits our plans for the future.

Thanks in advance, Tammo

**Comment by grakic** [comment]
Here is one easy fix to correct list item padding, add this next to `visibility: hidden;` rule:

```
input[type='radio'], input[type='checkbox'] {
    position: absolute;
}
```

![before_after](https://cloud.githubusercontent.com/assets/712022/7359278/d4305234-ed3c-11e4-8f0e-dd2dcc2338b0.png)

**Comment by tammoterhark** [comment]
Thank you. We also saw this flaw and are working on it (and some others). Thanks again, it will be solved in de next release.

**Comment by tammoterhark** [comment]
Issue resolved in newest release!
