### ISSUE TITLE
Values/answers of dual matrix questions are not being stored.

### ISSUE THREAD

**Issue by HellaHepp** [toolsforresearch/tfr_responsive#6]

**Comment by tammoterhark** [comment]
Hi HellaHepp, we will investigate! Thanks for mentioning this.

**Comment by tammoterhark** [comment]
We did investigate, but have not solved it in the current release. Will do this later.

**Comment by HellaHepp** [comment]
Thanks for the update! Looking forward to the fixed release!

**Comment by tammoterhark** [comment]
We added support for dual scale, it seems to work now. Can you confirm this?

# steps to take (important)
- Download the latest release
- unpack the release
- download js/template.js
- overwrite the js/template.js with the newest one

**Comment by HellaHepp** [comment]
Confirmed! Thank you very much for fixing it!
