### ISSUE TITLE
.warningjs seems not yet to be implemented in CSS.

### ISSUE THREAD

**Issue by HellaHepp** [toolsforresearch/tfr_responsive#9]
e. g.:

.warningjs {
color: red;
font-size: 2.0rem;
font-style: oblique;
font-weight: bold;
}

**Comment by HellaHepp** [comment]
e. g.:

.warningjs {
     color: red;
     font-size: 2.0rem;
     font-style: oblique; 
     font-weight: bold;
}

**Comment by tammoterhark** [comment]
Hi Hella, where&when is this class triggered?

**Comment by HellaHepp** [comment]
Hi Tammo,

"warningjs" is triggered when you start your survey with JavaScript disabled in your browser's settings. 

For more information see e. g.:

https://www.limesurvey.org/de/forum/design-issues/93332-in-what-file-do-i-find-the-noscript-message-caution-javascript-execution-is-d?q=/de/forum/design-issues/93332-in-what-file-do-i-find-the-noscript-message-caution-javascript-execution-is-d?q=/de/forum/design-issues/93332-in-what-file-do-i-find-the-noscript-message-caution-javascript-execution-is-d

Best regards and keep up the good work!
Hella

**Comment by tammoterhark** [comment]
This is implemented in our newest release which will be online next week.
